full_rebuild: true
name: Yu Jiang's Homepage
author: Yu Jiang (姜宇)
version: V 1.0
encoding: utf-8
defaults:
  -
    values:
      layout: "index"
markdown: kramdown
kramdown:
  input: GFM
relative_permalinks: false
collections:
- entries
sass:
  sass_dir: _sass
  style: :compressed
exclude: [
.git,
.gitignore,
README.md,
.sass-cache
]
